# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_buildings_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QMovie


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(788, 434)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 761, 391))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 759, 389))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 151, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 156, 23))
        self.label_2.setMinimumSize(QtCore.QSize(156, 23))
        self.label_2.setMaximumSize(QtCore.QSize(156, 23))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 156, 23))
        self.label_4.setMinimumSize(QtCore.QSize(156, 23))
        self.label_4.setMaximumSize(QtCore.QSize(156, 23))
        self.label_4.setObjectName("label_4")
        self.label_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_1.setGeometry(QtCore.QRect(20, 40, 156, 23))
        self.label_1.setMinimumSize(QtCore.QSize(156, 23))
        self.label_1.setMaximumSize(QtCore.QSize(156, 23))
        self.label_1.setObjectName("label_1")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(169, 20, 381, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_3.setGeometry(QtCore.QRect(190, 180, 341, 21))
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_1 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_1.setGeometry(QtCore.QRect(190, 40, 341, 21))
        self.toolButton_1.setObjectName("toolButton_1")
        self.toolButton_2 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_2.setGeometry(QtCore.QRect(190, 110, 341, 21))
        self.toolButton_2.setObjectName("toolButton_2")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(380, 220, 160, 80))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_5.addWidget(self.pushButton_2)
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setGeometry(QtCore.QRect(10, 220, 341, 151))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(380, 310, 158, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_gif = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_gif.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_gif.setObjectName("horizontalLayout_gif")
        self.description = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.description.setGeometry(QtCore.QRect(561, 21, 169, 351))
        self.description.setObjectName("description")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Minimum Bicycle and Car Parking Spaces for New Buildings"))
        self.label_2.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Weakspot = location that needs to have new waste facility</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "INPUT (new buildings)"))
        self.label_4.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Weakspot = location that needs to have new waste facility</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "Output"))
        self.label_1.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Weakspot = location that needs to have new waste facility</p></body></html>"))
        self.label_1.setText(_translate("Dialog", "INPUT (Buffer map)"))
        self.toolButton_3.setText(_translate("Dialog", "..."))
        self.toolButton_1.setText(_translate("Dialog", "..."))
        self.toolButton_2.setText(_translate("Dialog", "..."))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.description.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Calculate the minimum bicycle and car parking spaces for new buildings</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">For parameters:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; color:#3e3e3e;\">Input: Select the layer which contains buffer map for discount, new building data.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:10pt; color:#3e3e3e;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; color:#3e3e3e;\">Output: Select path to store the output CityJSON results.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,Microsoft YaHei,微软雅黑,宋体,Malgun Gothic,Meiryo,sans-serif\'; font-size:10pt; color:#333333;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:10pt; color:#3e3e3e;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; color:#3e3e3e;\">Click OK/Cancel to start/stop the processing.</span></p></body></html>"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    icon = QIcon("icon.PNG")
    app.setWindowIcon(icon)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

